'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const menu=document.getElementById('menu'),touchUi=document.getElementById('touchUi');
const startButton=document.getElementById('startButton'),teamSelect=document.getElementById('teamSelect');
const loading=document.getElementById('loading'),loadingCount=document.getElementById('loadingCount'),menuMessage=document.getElementById('menuMessage');
const W=1000,H=600,TOP=92,BOTTOM=535,GOAL_TOP=122,GOAL_BOTTOM=505,GROUND=0;
const keys=new Set(),pressed=new Set();let running=false,last=0,score=[0,0],time=90,message='',messageLife=0;
let joy={x:0,y:0,pointer:null};const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const norm=(x,y)=>{const d=Math.hypot(x,y)||1;return{x:x/d,y:y/d}};
const TEAM_DEFS=[
  {id:'blizzard_fox',name:'BLIZZARD FOX'},
  {id:'salvida_a',name:'SALVIDA A'},
  {id:'salvida_b',name:'SALVIDA B'},
  {id:'take_zo',name:'TAKE-ZO'},
  {id:'manchester_p',name:'漫チェスターP'}
];
const PLAYER_STATES=['idle','run','kick','jump_prep','jump','stumble','fly','down'];
const KEEPER_STATES=['idle','dive','down'];
const images={players:{},keepers:{left:{},right:{}},ball:{}};let selectedTeam=0,cpuTeam=1,assetsReady=false;
const assetJobs=[];
for(const t of TEAM_DEFS){images.players[t.id]={};for(const s of PLAYER_STATES)assetJobs.push({target:images.players[t.id],key:s,src:`assets/players/${t.id}/${s}.webp`});}
for(const side of ['left','right'])for(const s of KEEPER_STATES)assetJobs.push({target:images.keepers[side],key:s,src:`assets/keepers/${side}/${s}.webp`});
for(const s of ['matte','glossy'])assetJobs.push({target:images.ball,key:s,src:`assets/ball/${s}.webp`});
function loadAssets(){let done=0;loadingCount.textContent=`0 / ${assetJobs.length}`;return Promise.all(assetJobs.map(job=>new Promise(resolve=>{const img=new Image();img.onload=img.onerror=()=>{job.target[job.key]=img;done++;loadingCount.textContent=`${done} / ${assetJobs.length}`;resolve();};img.src=job.src;}))).then(()=>{assetsReady=true;startButton.disabled=false;startButton.textContent='スタート';loading.classList.add('done');});}
function buildTeamSelect(){TEAM_DEFS.forEach((t,i)=>{const b=document.createElement('button');b.type='button';b.className='team-card'+(i===0?' selected':'');b.innerHTML=`<img src="assets/players/${t.id}/idle.webp" alt=""><span>${t.name}</span>`;b.addEventListener('click',()=>{selectedTeam=i;document.querySelectorAll('.team-card').forEach((x,n)=>x.classList.toggle('selected',n===i));});teamSelect.appendChild(b);});}
function makePlayer(side,x,y,teamIndex){return{side,teamIndex,x,y,z:0,vx:0,vy:0,vz:0,r:24,aimX:side?-1:1,aimY:0,charge:0,kickCd:0,kickFx:0,jumpCd:0,jumpPrep:0,pendingJump:false,stun:0,down:0,inv:0,kickGuard:0}}
function makeKeeper(side,x,y){return{side,x,y,homeX:x,homeY:y,z:0,vx:0,vy:0,vz:0,r:28,down:0,inv:0,dive:0}}
let ball,players,keepers,effects=[];
function reset(afterGoal=false){ball={x:500,y:310,z:0,vx:afterGoal?0:(Math.random()<.5?-80:80),vy:0,vz:0,r:55,spin:0,squash:0,special:0};players=[makePlayer(0,270,310,selectedTeam),makePlayer(1,730,310,cpuTeam)];keepers=[makeKeeper(0,72,310),makeKeeper(1,928,310)];effects=[];}
function start(){if(!assetsReady)return;cpuTeam=(selectedTeam+1+Math.floor(Math.random()*(TEAM_DEFS.length-1)))%TEAM_DEFS.length;score=[0,0];time=90;message='KICK OFF!';messageLife=1.2;reset();running=true;last=performance.now();menu.style.display='none';touchUi.hidden=false;requestAnimationFrame(loop)}
function inputVector(){let x=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+joy.x,y=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+joy.y;const d=Math.hypot(x,y);return d>1?{x:x/d,y:y/d}:{x,y}}
const tier=v=>v>=1?4:v>=.75?3:v>=.5?2:v>=.25?1:0;
function kick(p){if(p.kickCd>0||p.down>0||p.stun>0)return;p.kickCd=.28;p.kickFx=.2;const dx=ball.x-p.x,dy=ball.y-p.y,dist=Math.hypot(dx,dy),dz=ball.z-(p.z+20);if(dist>p.r+ball.r+42||Math.abs(dz)>115)return;let dir=norm(p.aimX,p.aimY);const incoming=ball.vx*(p.x-ball.x)+ball.vy*(p.y-ball.y)>0,just=incoming&&dist<p.r+ball.r+18&&Math.hypot(ball.vx,ball.vy)>210;if(just){const back=norm(-ball.vx,-ball.vy);dir=norm(dir.x*.55+back.x*.45,dir.y*.55+back.y*.45)}const t=tier(p.charge),power=(410+t*92)*(just?1.3:1);ball.vx=dir.x*power;ball.vy=dir.y*power;ball.vz=340+t*55+(p.z>0?175:0);ball.squash=.17;ball.special=(t===4||just)?.5:0;p.kickGuard=.15;const cost=[0,.12,.22,.34,.48][t];p.charge=Math.max(0,p.charge-cost);effects.push({x:ball.x,y:ball.y,life:.35,max:.35,just});if(just){message='JUST KICK!';messageLife=.55}}
function jump(p){if(p.jumpCd||p.down||p.stun||p.z>1||p.jumpPrep>0)return;p.jumpPrep=.11;p.pendingJump=true;p.jumpCd=.48}
function movePlayer(p,dt,input,charging){p.kickCd=Math.max(0,p.kickCd-dt);p.kickFx=Math.max(0,p.kickFx-dt);p.jumpCd=Math.max(0,p.jumpCd-dt);p.stun=Math.max(0,p.stun-dt);p.down=Math.max(0,p.down-dt);p.inv=Math.max(0,p.inv-dt);p.kickGuard=Math.max(0,p.kickGuard-dt);if(p.jumpPrep>0){p.jumpPrep-=dt;if(p.jumpPrep<=0&&p.pendingJump){p.pendingJump=false;p.vz=735}}if(p.down>0){p.vx*=Math.pow(.89,dt*60);p.vy*=Math.pow(.89,dt*60)}else if(p.stun>0){p.vx*=Math.pow(.86,dt*60);p.vy*=Math.pow(.86,dt*60)}else if(p.jumpPrep<=0){if(charging)p.charge=Math.min(1,p.charge+dt*.29);const speed=charging?170:285;p.vx+=(input.x*speed-p.vx)*Math.min(1,dt*12);p.vy+=(input.y*speed-p.vy)*Math.min(1,dt*12);if(Math.hypot(input.x,input.y)>.1){p.aimX=input.x;p.aimY=input.y}}p.x+=p.vx*dt;p.y+=p.vy*dt;p.vz-=1480*dt;p.z+=p.vz*dt;if(p.z<0){p.z=0;p.vz=0}p.x=clamp(p.x,110,890);p.y=clamp(p.y,TOP+25,BOTTOM-25)}
function cpu(p){const tx=ball.x+(ball.vx*.16)+(ball.x>700?-70:20),ty=ball.y+ball.vy*.16,n=norm(tx-p.x,ty-p.y),d=Math.hypot(ball.x-p.x,ball.y-p.y);p.chargeIntent=d>260&&p.charge<.82;if(d<p.r+ball.r+36&&p.kickCd<=0)kick(p);if(ball.z>65&&d<145&&p.z===0)jump(p);return n}
function hitPerson(p,keeper=false){if(p.inv>0||(!keeper&&p.kickGuard>0))return;const dx=p.x-ball.x,dy=p.y-ball.y,d=Math.hypot(dx,dy),m=p.r+ball.r;if(d>=m||ball.z>112+p.z)return;const n=d>.01?{x:dx/d,y:dy/d}:{x:p.side?-1:1,y:0},speed=Math.hypot(ball.vx,ball.vy),airborne=!keeper&&p.z>18,o=m-d;p.x+=n.x*o*.5;p.y+=n.y*o*.5;if(speed>20||airborne){if(speed<175&&!airborne&&!keeper){p.stun=.28;p.vx=n.x*110;p.vy=n.y*110}else{const hs=Math.max(speed,airborne?245:0);p.down=keeper?1.15:clamp(.55+hs/600,.65,1.4);p.inv=p.down+.25;p.vx=n.x*clamp(hs*.8,220,470);p.vy=n.y*clamp(hs*.8,220,470);p.vz=airborne?355:keeper?275:220}ball.vx*=keeper?.48:.7;ball.vy*=keeper?.48:.7;ball.vz=Math.max(ball.vz,keeper?350:285+Math.min(200,speed*.3));ball.squash=.18}}
function keeper(k,dt){k.down=Math.max(0,k.down-dt);k.inv=Math.max(0,k.inv-dt);if(k.down>0){k.x+=k.vx*dt;k.y+=k.vy*dt;k.vx*=Math.pow(.9,dt*60);k.vy*=Math.pow(.9,dt*60)}else{const toward=k.side?ball.vx>0:ball.vx<0,close=k.side?ball.x>690:ball.x<310,target=toward&&close?clamp(ball.y,GOAL_TOP+20,GOAL_BOTTOM-20):k.homeY;k.vy=clamp((target-k.y)*8,-470,470);k.dive=Math.abs(k.vy)>170?.18:Math.max(0,k.dive-dt);k.y+=k.vy*dt;k.x+=(k.homeX-k.x)*Math.min(1,dt*6)}k.vz-=1400*dt;k.z+=k.vz*dt;if(k.z<0){k.z=0;k.vz=0}k.y=clamp(k.y,GOAL_TOP+18,GOAL_BOTTOM-18);hitPerson(k,true)}
function ballUpdate(dt){ball.vz-=780*dt;ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;ball.z+=ball.vz*dt;ball.vx*=Math.pow(.995,dt*60);ball.vy*=Math.pow(.995,dt*60);ball.spin+=Math.hypot(ball.vx,ball.vy)*dt*.009;ball.squash=Math.max(0,ball.squash-dt);ball.special=Math.max(0,ball.special-dt);if(ball.z<GROUND){ball.z=GROUND;if(Math.abs(ball.vz)>55){ball.vz=-ball.vz*.88;ball.squash=.13}else ball.vz=0;ball.vx*=.988;ball.vy*=.988}if(ball.y-ball.r<TOP){ball.y=TOP+ball.r;ball.vy=Math.abs(ball.vy)*.84;ball.squash=.1}if(ball.y+ball.r>BOTTOM){ball.y=BOTTOM-ball.r;ball.vy=-Math.abs(ball.vy)*.84;ball.squash=.1}const mouth=ball.y>GOAL_TOP&&ball.y<GOAL_BOTTOM;if(!mouth){if(ball.x-ball.r<45){ball.x=45+ball.r;ball.vx=Math.abs(ball.vx)*.76}else if(ball.x+ball.r>955){ball.x=955-ball.r;ball.vx=-Math.abs(ball.vx)*.76}}if(mouth&&ball.z<185){if(ball.x<-15)goal(1);else if(ball.x>1015)goal(0)}}
function goal(team){score[team]++;message=team===0?'GOAL!':'CPU GOAL';messageLife=1.4;if(score[team]>=3){running=false;setTimeout(()=>showMenu(team===0?'勝利！ 同じチームでもう一度遊べます。':'敗北… チームを選び直して再挑戦！'),900)}else reset(true)}
function showMenu(text){menu.style.display='grid';touchUi.hidden=true;menuMessage.textContent=text}
function update(dt){time=Math.max(0,time-dt);messageLife=Math.max(0,messageLife-dt);effects.forEach(e=>e.life-=dt);effects=effects.filter(e=>e.life>0);const p=players[0],inp=inputVector();movePlayer(p,dt,inp,keys.has('KeyL'));if(pressed.has('KeyJ'))kick(p);if(pressed.has('KeyK'))jump(p);const c=players[1],ci=cpu(c);movePlayer(c,dt,ci,c.chargeIntent);ballUpdate(dt);players.forEach(p=>hitPerson(p));keepers.forEach(k=>keeper(k,dt));pressed.clear();if(time<=0){running=false;message=score[0]===score[1]?'DRAW':score[0]>score[1]?'WIN!':'LOSE';setTimeout(()=>showMenu(score[0]===score[1]?'引き分け。もう一度スタートできます。':score[0]>score[1]?'勝利！ もう一度スタートできます。':'敗北… 再挑戦！'),900)}}
function drawField(){ctx.fillStyle='#183d31';ctx.fillRect(0,0,W,H);for(let i=0;i<10;i++){ctx.fillStyle=i%2?'#1d4939':'#20503e';ctx.fillRect(i*100,TOP,100,BOTTOM-TOP)}ctx.strokeStyle='#dbeed5aa';ctx.lineWidth=5;ctx.strokeRect(45,TOP,910,BOTTOM-TOP);ctx.beginPath();ctx.moveTo(500,TOP);ctx.lineTo(500,BOTTOM);ctx.stroke();ctx.beginPath();ctx.arc(500,310,88,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#cfe8dd18';ctx.fillRect(45,GOAL_TOP,95,GOAL_BOTTOM-GOAL_TOP);ctx.fillRect(860,GOAL_TOP,95,GOAL_BOTTOM-GOAL_TOP);ctx.strokeStyle='#fff';ctx.lineWidth=8;ctx.strokeRect(4,GOAL_TOP,42,GOAL_BOTTOM-GOAL_TOP);ctx.strokeRect(954,GOAL_TOP,42,GOAL_BOTTOM-GOAL_TOP)}
function shadow(x,y,z,r){ctx.fillStyle=`rgba(0,0,0,${.28-clamp(z/600,0,.18)})`;ctx.beginPath();ctx.ellipse(x,y+r*.7,r*(1-z/900),r*.28*(1-z/900),0,0,Math.PI*2);ctx.fill()}
function playerState(p){if(p.down>0)return p.z>8||Math.hypot(p.vx,p.vy)>150?'fly':'down';if(p.stun>0)return'stumble';if(p.kickFx>0)return'kick';if(p.jumpPrep>0)return'jump_prep';if(p.z>1)return'jump';if(Math.hypot(p.vx,p.vy)>55)return'run';return'idle'}
function drawSprite(img,x,y,z,state,flip=false,keeper=false){if(!img||!img.complete)return;let maxH=keeper?108:116,maxW=keeper?130:145;if(state==='run'){maxH=125;maxW=155}else if(state==='fly'||state==='down'){maxH=92;maxW=155}else if(state==='kick'){maxH=122;maxW=145}else if(state==='jump'){maxH=112;maxW=130}const s=Math.min(maxW/img.naturalWidth,maxH/img.naturalHeight),dw=img.naturalWidth*s,dh=img.naturalHeight*s;ctx.save();ctx.translate(x,y-z);if(flip)ctx.scale(-1,1);ctx.drawImage(img,-dw/2,-dh+22,dw,dh);ctx.restore()}
function drawPerson(p,keeper=false){shadow(p.x,p.y,p.z,p.r);if(keeper){const side=p.side?'right':'left',state=p.down>0?'down':p.dive>0?'dive':'idle';drawSprite(images.keepers[side][state],p.x,p.y,p.z,state,false,true)}else{const state=playerState(p),team=TEAM_DEFS[p.teamIndex].id,flip=p.aimX>0;drawSprite(images.players[team][state],p.x,p.y,p.z,state,flip,false);ctx.fillStyle='#07111dcc';ctx.fillRect(p.x-35,p.y-p.z-76,70,8);ctx.fillStyle=p.side?'#ff7282':'#64b7ff';ctx.fillRect(p.x-35,p.y-p.z-76,70*p.charge,8)}}
function drawBall(){shadow(ball.x,ball.y,ball.z,ball.r);const img=ball.special>0?images.ball.glossy:images.ball.matte;if(!img||!img.complete)return;ctx.save();ctx.translate(ball.x,ball.y-ball.z);if(ball.special<=0)ctx.rotate(ball.spin);const sq=ball.squash>0?Math.sin(ball.squash/.18*Math.PI)*.16:0,pulse=ball.special>0?1+Math.sin(performance.now()*.018)*.035:1;ctx.scale((1+sq)*pulse,(1-sq)*pulse);ctx.drawImage(img,-ball.r,-ball.r,ball.r*2,ball.r*2);ctx.restore()}
function drawHud(){ctx.fillStyle='#07111dcc';ctx.fillRect(0,0,W,76);ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='900 39px system-ui';ctx.fillText(`${score[0]}  -  ${score[1]}`,500,49);ctx.textAlign='left';ctx.font='800 18px system-ui';ctx.fillStyle='#72bdff';ctx.fillText(TEAM_DEFS[selectedTeam].name,26,43);ctx.textAlign='right';ctx.fillStyle='#ff7785';ctx.fillText(TEAM_DEFS[cpuTeam].name,974,43);ctx.textAlign='center';ctx.fillStyle='#fff8b6';ctx.font='800 18px system-ui';ctx.fillText(`${Math.ceil(time)} sec`,500,70);if(messageLife>0){ctx.font='900 52px system-ui';ctx.fillStyle='#fff';ctx.strokeStyle='#07334b';ctx.lineWidth=9;ctx.strokeText(message,500,145);ctx.fillText(message,500,145)}}
function draw(){drawField();keepers.forEach(k=>drawPerson(k,true));players.forEach(p=>drawPerson(p));drawBall();drawHud()}
function loop(now){if(!running)return;const dt=Math.min(.033,(now-last)/1000||.016);last=now;update(dt);draw();requestAnimationFrame(loop)}
window.addEventListener('keydown',e=>{if(!keys.has(e.code))pressed.add(e.code);keys.add(e.code);if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault()});window.addEventListener('keyup',e=>keys.delete(e.code));
startButton.addEventListener('click',start);
function bindButton(id,code){const b=document.getElementById(id);const on=e=>{e.preventDefault();if(!keys.has(code))pressed.add(code);keys.add(code);b.classList.add('active');try{b.setPointerCapture(e.pointerId)}catch{}};const off=e=>{e.preventDefault();keys.delete(code);b.classList.remove('active')};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off)}bindButton('kickButton','KeyJ');bindButton('jumpButton','KeyK');bindButton('chargeButton','KeyL');
const joyEl=document.getElementById('joystick'),stick=document.getElementById('stick');function joyMove(e){if(joy.pointer!==e.pointerId)return;const r=joyEl.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),max=r.width*.32,d=Math.hypot(dx,dy),s=d>max?max/d:1,px=dx*s,py=dy*s;joy.x=px/max;joy.y=py/max;stick.style.transform=`translate(${px}px,${py}px)`}joyEl.addEventListener('pointerdown',e=>{e.preventDefault();joy.pointer=e.pointerId;joyEl.setPointerCapture(e.pointerId);joyMove(e)});joyEl.addEventListener('pointermove',joyMove);function joyEnd(e){if(joy.pointer!==e.pointerId)return;joy.pointer=null;joy.x=joy.y=0;stick.style.transform='translate(0,0)'}joyEl.addEventListener('pointerup',joyEnd);joyEl.addEventListener('pointercancel',joyEnd);
buildTeamSelect();reset();draw();loadAssets().then(draw);
