

function drawShootingTraining(){
 ctx.save();
 ctx.fillStyle='#06101b';ctx.fillRect(0,100,W,H-100);ctx.fillStyle='#0d2636';ctx.fillRect(65,125,285,780);ctx.strokeStyle='#5bd7ff';ctx.lineWidth=4;ctx.strokeRect(65,125,285,780);
 ctx.fillStyle='#9fe8ff';ctx.font='bold 18px sans-serif';ctx.textAlign='center';ctx.fillText('移動可能エリア',207,155);
 for(const t of shootingTargets){ctx.save();ctx.translate(t.x,t.y);ctx.strokeStyle=t.kind==='gold'?'#ffe46b':t.kind==='small'?'#9fe8ff':'#ffb27a';ctx.fillStyle=t.kind==='gold'?'#6f5515':t.kind==='small'?'#184c67':'#6d3023';ctx.lineWidth=6;ctx.beginPath();ctx.arc(0,0,t.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle='#f7fbff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,t.r*.5,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(-t.r,0);ctx.lineTo(t.r,0);ctx.moveTo(0,-t.r);ctx.lineTo(0,t.r);ctx.stroke();ctx.restore()}
 for(const b of shootingBullets){ctx.save();ctx.translate(b.x,b.y);if(b.type==='shuriken'){ctx.rotate(performance.now()/75);ctx.fillStyle=b.ownerType==='fox'?'#f5fdff':'#dbe7ff';ctx.strokeStyle=b.ownerType==='fox'?'#4ca6df':'#5c79a8';ctx.lineWidth=2;for(let k=0;k<4;k++){ctx.rotate(Math.PI/2);ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(17,5);ctx.lineTo(7,0);ctx.lineTo(17,-5);ctx.closePath();ctx.fill();ctx.stroke()}}else{ctx.fillStyle=b.ownerType==='archmage'?'#5fa8ff':'#ff753b';ctx.shadowBlur=18;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.arc(0,0,b.r,0,Math.PI*2);ctx.fill()}ctx.restore()}
 heroes[0]?.draw(0);
 ctx.fillStyle='#ffffff';ctx.textAlign='center';ctx.font='bold 31px sans-serif';ctx.fillText(`SCORE ${shootingScore}`,600,105);ctx.font='bold 22px sans-serif';ctx.fillText(`COMBO ${shootingCombo}`,600,140);ctx.font='bold 18px sans-serif';ctx.fillStyle='#d8e8f4';ctx.fillText('方向キー：左エリア内を移動　A：射撃',500,930);ctx.restore()
}


function drawPrecisionShootingTraining(){
 ctx.save();
 ctx.fillStyle='#07111d';ctx.fillRect(0,100,W,H-100);
 ctx.fillStyle='#10243a';ctx.fillRect(90,125,190,740);ctx.strokeStyle='#5bd7ff';ctx.lineWidth=4;ctx.strokeRect(90,125,190,740);
 ctx.fillStyle='#9fe8ff';ctx.font='bold 18px sans-serif';ctx.textAlign='center';ctx.fillText('上下移動エリア',185,155);
 ctx.fillStyle='#231d18';ctx.fillRect(755,125,190,740);ctx.strokeStyle='#ffd66b';ctx.lineWidth=4;ctx.strokeRect(755,125,190,740);
 ctx.strokeStyle='#ffffff22';ctx.lineWidth=2;for(let x=790;x<=910;x+=60){ctx.beginPath();ctx.moveTo(x,125);ctx.lineTo(x,865);ctx.stroke()}
 ctx.fillStyle='#ffd66b';ctx.fillText('的の流れるレーン',850,155);
 ctx.strokeStyle='#ffffff18';ctx.setLineDash([12,12]);ctx.beginPath();ctx.moveTo(285,500);ctx.lineTo(750,500);ctx.stroke();ctx.setLineDash([]);
 for(const t of precisionTargets){ctx.save();ctx.translate(t.x,t.y);if(t.hitFlash>0){ctx.shadowBlur=24;ctx.shadowColor='#fff3a0'}if(t.freezeFlash>0){ctx.shadowBlur=26;ctx.shadowColor='#72dfff'}else if(t.burnFlash>0){ctx.shadowBlur=24;ctx.shadowColor='#ff7a35'}ctx.fillStyle=t.freezeFlash>0?'#dff8ff':'#f4f0df';ctx.strokeStyle='#5d3b20';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,t.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#e94d45';ctx.beginPath();ctx.arc(0,0,t.r*.62,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f7f1df';ctx.beginPath();ctx.arc(0,0,t.r*.34,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e94d45';ctx.beginPath();ctx.arc(0,0,t.r*.14,0,Math.PI*2);ctx.fill();if(t.freezeFlash>0){ctx.shadowBlur=0;ctx.strokeStyle='#79dcff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-t.r*.72,-t.r*.1);ctx.lineTo(t.r*.65,t.r*.22);ctx.moveTo(-t.r*.35,-t.r*.62);ctx.lineTo(t.r*.28,t.r*.7);ctx.stroke()}if(t.burnFlash>0){ctx.shadowBlur=0;ctx.fillStyle='#ff8a38';ctx.beginPath();ctx.moveTo(-8,-t.r-4);ctx.quadraticCurveTo(-20,-t.r-24,-4,-t.r-34);ctx.quadraticCurveTo(3,-t.r-20,10,-t.r-8);ctx.quadraticCurveTo(18,-t.r-24,22,-t.r-4);ctx.closePath();ctx.fill()}ctx.restore()}
 for(const b of precisionBullets){ctx.save();ctx.translate(b.x,b.y);if(b.type==='shuriken'){ctx.rotate(performance.now()/75);ctx.fillStyle=b.ownerType==='fox'?'#f5fdff':'#dbe7ff';ctx.strokeStyle='#5c79a8';ctx.lineWidth=2;for(let k=0;k<4;k++){ctx.rotate(Math.PI/2);ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(16,5);ctx.lineTo(7,0);ctx.lineTo(16,-5);ctx.closePath();ctx.fill();ctx.stroke()}}else{ctx.fillStyle=b.type==='freeze'?'#75dcff':'#ff753b';ctx.shadowBlur=14;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.arc(0,0,b.r,0,Math.PI*2);ctx.fill()}ctx.restore()}
 heroes[0]?.draw(0);
 for(const f of precisionJudgeFx){ctx.save();ctx.globalAlpha=Math.min(1,f.life*2);ctx.fillStyle=f.color;ctx.textAlign='center';ctx.font='bold 28px sans-serif';ctx.fillText(f.text,f.x,f.y);ctx.restore()}
 ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='bold 31px sans-serif';ctx.fillText(`SCORE ${precisionScore}`,500,105);ctx.font='bold 22px sans-serif';ctx.fillText(`COMBO ${precisionCombo}`,500,140);ctx.font='bold 18px sans-serif';ctx.fillStyle='#e8edf2';ctx.fillText('方向キー：上下移動　A：右へ射撃　中心100 / 内側50 / 外側20　複数弾は各弾加点',500,930);ctx.restore()
}

function drawMoleTraining(){
 ctx.save();
 for(let i=0;i<MOLE_HOLES.length;i++){const [x,y]=MOLE_HOLES[i];ctx.fillStyle='#090705';ctx.beginPath();ctx.ellipse(x,y+18,60,25,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#6d5841';ctx.lineWidth=6;ctx.stroke();ctx.fillStyle='#0009';ctx.beginPath();ctx.ellipse(x,y+15,46,16,0,0,Math.PI*2);ctx.fill()}
 for(const m of moles){const [x,y]=MOLE_HOLES[m.hole];if(m.warn>0){const p=1-m.warn/.15;ctx.globalAlpha=.35+.45*p;ctx.fillStyle='#6f5134';ctx.beginPath();ctx.ellipse(x,y+8,38+8*p,13+4*p,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;continue}const rise=Math.min(1,(m.max-m.life)/.12,m.life/.12);const yy=y+18-rise*58;ctx.save();ctx.translate(x,yy);ctx.fillStyle=m.kind==='king'?'#8b5b23':m.kind==='gold'?'#d9a72f':'#704628';ctx.strokeStyle=m.kind==='king'?'#ffe278':m.kind==='gold'?'#fff0a1':'#b98758';ctx.lineWidth=4;ctx.beginPath();ctx.roundRect(-33,-42,66,72,25);ctx.fill();ctx.stroke();ctx.fillStyle='#18110c';ctx.beginPath();ctx.arc(-11,-17,4,0,Math.PI*2);ctx.arc(11,-17,4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e7b18b';ctx.beginPath();ctx.ellipse(0,-3,10,7,0,0,Math.PI*2);ctx.fill();if(m.kind==='king'){ctx.fillStyle='#ffe267';ctx.beginPath();ctx.moveTo(-25,-43);ctx.lineTo(-14,-65);ctx.lineTo(0,-48);ctx.lineTo(14,-65);ctx.lineTo(25,-43);ctx.closePath();ctx.fill()}ctx.restore()}
 if(heroes[0])heroes[0].draw(0);
 if(moleAttackFx>0){const a={left:Math.PI,up:-Math.PI/2,down:Math.PI/2,right:0,upLeft:-Math.PI*3/4,upRight:-Math.PI/4,downLeft:Math.PI*3/4,downRight:Math.PI/4}[moleAttackDir]||0;ctx.save();const h=heroes[0];ctx.translate(h?h.x:500,h?h.y:525);ctx.rotate(a);ctx.globalAlpha=moleAttackFx/.13;ctx.strokeStyle='#fff4cf';ctx.shadowBlur=20;ctx.shadowColor='#ffd27b';ctx.lineWidth=24;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(42,0);ctx.lineTo(190,0);ctx.stroke();ctx.strokeStyle='#ffffff';ctx.lineWidth=7;ctx.stroke();ctx.restore()}
 ctx.fillStyle='#ffffff';ctx.textAlign='center';ctx.font='bold 30px sans-serif';ctx.fillText(`SCORE ${moleScore}`,500,105);ctx.font='bold 22px sans-serif';ctx.fillText(`COMBO ${moleCombo}`,500,140);ctx.font='bold 18px sans-serif';ctx.fillStyle='#d8e8f4';ctx.fillText('方向キー：移動　A左・B上・C下・D右　斜め入力＋隣接ボタンで斜め攻撃',500,920);ctx.restore()
}
function drawDoor(x,dir){ctx.save();ctx.translate(x,525);ctx.fillStyle='#171b22';ctx.fillRect(dir<0?-55:0,-105,55,210);ctx.strokeStyle='#9d8a5c';ctx.lineWidth=9;ctx.strokeRect(dir<0?-55:0,-105,55,210);ctx.strokeStyle='#514833';ctx.lineWidth=6;for(let y=-72;y<=72;y+=36){ctx.beginPath();ctx.moveTo(dir<0?-49:6,y);ctx.lineTo(dir<0?-6:49,y);ctx.stroke()}ctx.fillStyle='#d7b85e';ctx.beginPath();ctx.arc(dir<0?-16:16,0,8,0,Math.PI*2);ctx.fill();
ctx.strokeStyle='#888';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(dir<0?-52:3,-70);ctx.lineTo(dir<0?-3:52,70);ctx.moveTo(dir<0?-3:52,-70);ctx.lineTo(dir<0?-52:3,70);ctx.stroke();ctx.restore()}
function drawArena(){ctx.fillStyle='#11141a';ctx.fillRect(0,0,W,H);const g=ctx.createRadialGradient(500,520,100,500,520,580);g.addColorStop(0,'#4b4944');g.addColorStop(1,'#25272b');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(250,120);ctx.lineTo(750,120);ctx.lineTo(930,300);ctx.lineTo(930,750);ctx.lineTo(750,930);ctx.lineTo(250,930);ctx.lineTo(70,750);ctx.lineTo(70,300);ctx.closePath();ctx.fill();ctx.strokeStyle='#b6a472';ctx.lineWidth=16;ctx.stroke();ctx.strokeStyle='#ffffff24';ctx.lineWidth=4;ctx.beginPath();ctx.arc(500,525,95,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(500,135);ctx.lineTo(500,915);ctx.stroke();for(let i=0;i<20;i++){const a=i*2.399,r=170+(i%5)*65;ctx.fillStyle='#ffffff12';ctx.beginPath();ctx.arc(500+Math.cos(a)*r,525+Math.sin(a)*r,4+(i%3)*2,0,Math.PI*2);ctx.fill()}drawDoor(72,-1);drawDoor(928,1)}
function draw(){
 ctx.save();
 if(shake>0){ctx.translate(rnd(-shake,shake),rnd(-shake,shake));shake*=.84}
 drawArena();
 if(trainingMode&&trainingChallenge==='soccer'){drawSoccerGame();ctx.restore();ctx.globalAlpha=1;return}
 if(trainingMode&&trainingChallenge==='mole'){drawMoleTraining();ctx.restore();ctx.globalAlpha=1;return}if(trainingMode&&trainingChallenge==='shooting'){drawShootingTraining();ctx.restore();ctx.globalAlpha=1;return}if(trainingMode&&trainingChallenge==='precision'){drawPrecisionShootingTraining();ctx.restore();ctx.globalAlpha=1;return}
 if(trainingMode){for(let i=0;i<TRAINING_SPAWN_POINTS.length;i++){const [x,y]=TRAINING_SPAWN_POINTS[i],flash=trainingSpawnFlash[i]||0,pulse=1+flash*1.1;ctx.save();ctx.translate(x,y);ctx.scale(pulse,pulse);ctx.globalAlpha=.42+flash*.9;ctx.strokeStyle=flash>0?'#6f7680':'#050607';ctx.fillStyle='#00000055';ctx.lineWidth=flash>0?8:6;ctx.beginPath();ctx.arc(0,0,31,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-16,-16);ctx.lineTo(16,16);ctx.moveTo(16,-16);ctx.lineTo(-16,16);ctx.stroke();ctx.restore()}}
 if(!boss||!heroes.length){ctx.restore();ctx.globalAlpha=1;return}
 for(const r of runes){const p=.5+.5*Math.sin(r.pulse),col=r.kind==='fire'?'#ff6b35':r.kind==='ice'?'#74d4ff':'#ffe45c';ctx.save();ctx.translate(r.x,r.y);ctx.globalAlpha=.13+.07*p;ctx.strokeStyle=col;ctx.lineWidth=3;ctx.shadowBlur=8;ctx.shadowColor=col;ctx.beginPath();ctx.arc(0,0,r.r,0,Math.PI*2);ctx.stroke();ctx.rotate(r.pulse*.18);ctx.beginPath();for(let k=0;k<6;k++){const a=k*Math.PI/3;ctx.moveTo(Math.cos(a)*12,Math.sin(a)*12);ctx.lineTo(Math.cos(a)*r.r*.72,Math.sin(a)*r.r*.72)}ctx.stroke();ctx.restore()}
 for(const w of walls){
 const wx=(w.type==='qigong'||w.type==='foxIce')?w.x:w.owner.x,wy=(w.type==='qigong'||w.type==='foxIce')?w.y:w.owner.y;ctx.save();ctx.translate(wx,wy);
 const pulse=1+Math.sin(performance.now()/110)*.03;ctx.scale(pulse,pulse);
 if(w.type==='foxIce'){ctx.globalAlpha=.24;ctx.fillStyle='#9ee8ff';ctx.beginPath();ctx.ellipse(0,8,w.r*.72,w.r*.34,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.9;ctx.fillStyle='#bcefff';ctx.strokeStyle='#effcff';ctx.lineWidth=3;for(let k=-2;k<=2;k++){const x=k*18,h=52-Math.abs(k)*7;ctx.beginPath();ctx.moveTo(x-14,24);ctx.lineTo(x,-h);ctx.lineTo(x+14,24);ctx.closePath();ctx.fill();ctx.stroke()}}else if(w.type==='qigong'){const ratio=Math.max(0,w.hits/w.maxHits);ctx.globalAlpha=.09+.08*ratio;ctx.fillStyle='#7feaff';ctx.beginPath();ctx.arc(0,0,w.r,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.72;ctx.strokeStyle='#b9f7ff';ctx.shadowBlur=18;ctx.shadowColor='#59dfff';ctx.lineWidth=7;ctx.beginPath();ctx.arc(0,0,w.r,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=.38;ctx.lineWidth=3;for(let k=0;k<3;k++){ctx.beginPath();ctx.arc(0,0,w.r-18-k*18,(performance.now()/900+k)*.7,(performance.now()/900+k)*.7+Math.PI*1.25);ctx.stroke()}ctx.globalAlpha=.8;ctx.fillStyle='#d8fbff';ctx.font='bold 22px sans-serif';ctx.textAlign='center';ctx.fillText(`${Math.max(0,w.hits)}/30`,0,-w.r-12)}else{ctx.globalAlpha=.20;ctx.fillStyle='#eadcff';ctx.beginPath();ctx.arc(0,0,w.r,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.82;ctx.strokeStyle='#f3e8ff';ctx.lineWidth=10;ctx.beginPath();ctx.arc(0,0,w.r,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=.42;ctx.strokeStyle='#b78cff';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,w.r-14,0,Math.PI*2);ctx.stroke()}
 ctx.restore()
}
 for(const m of minions){
 ctx.save();ctx.globalAlpha=.22;ctx.fillStyle='#000';ctx.beginPath();ctx.ellipse(m.x,m.y+15,m.r+7,8,0,0,Math.PI*2);ctx.fill();
 ctx.globalAlpha=1;ctx.fillStyle=m.strong?'#77248f':'#4f3269';ctx.beginPath();ctx.arc(m.x,m.y,m.r,0,Math.PI*2);ctx.fill();
 ctx.fillStyle='#ff73dd';ctx.beginPath();ctx.arc(m.x-7,m.y-5,3,0,Math.PI*2);ctx.arc(m.x+7,m.y-5,3,0,Math.PI*2);ctx.fill();
 ctx.fillStyle='#17131d';ctx.fillRect(m.x-m.r,m.y-m.r-10,m.r*2,5);ctx.fillStyle='#c77cff';ctx.fillRect(m.x-m.r,m.y-m.r-10,m.r*2*Math.max(0,m.hp/m.maxHp),5);ctx.restore()
}
boss.draw();heroes.forEach((h,i)=>h.draw(i));
 for(const s of shots){ctx.save();ctx.translate(s.x,s.y);ctx.fillStyle=s.type==='fire'?'#ff7c36':s.type==='freeze'||s.type==='ice'?'#aeefff':s.type==='thunder'?'#ffe45c':s.type==='holy'?'#fff6a8':s.type==='ki'?'#7dffd8':s.type==='qigong'?'#ffd36a':s.type==='dragonfire'?'#ff6a32':s.type==='darkblade'?'#b066ff':s.type==='foxfire'?'#bdf4ff':s.type==='foxshuriken'?'#e8f8ff':'#ff725e';ctx.shadowBlur=s.type==='holy'?22:12;ctx.shadowColor=ctx.fillStyle;if(s.type==='bat'){const a=Math.atan2(s.vy,s.vx);ctx.rotate(a);ctx.fillStyle='#46132d';ctx.strokeStyle='#d8517d';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-14,0);ctx.quadraticCurveTo(-6,-12,0,-3);ctx.quadraticCurveTo(6,-12,14,0);ctx.quadraticCurveTo(7,7,0,3);ctx.quadraticCurveTo(-7,7,-14,0);ctx.fill();ctx.stroke();ctx.fillStyle='#ff5b83';ctx.beginPath();ctx.arc(2,-1,2,0,Math.PI*2);ctx.fill()}else if(s.type==='shuriken'||s.type==='foxshuriken'){const a=Math.atan2(s.vy,s.vx)+performance.now()/80;ctx.rotate(a);ctx.fillStyle=s.type==='foxshuriken'?'#f7fdff':'#dce8ff';ctx.strokeStyle=s.type==='foxshuriken'?'#4e9bd8':'#5f7fae';ctx.lineWidth=2;for(let k=0;k<4;k++){ctx.rotate(Math.PI/2);ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(18,5);ctx.lineTo(8,0);ctx.lineTo(18,-5);ctx.closePath();ctx.fill();ctx.stroke()}}else if(s.type==='darkblade'&&s.crescent){const a=Math.atan2(s.vy,s.vx);ctx.rotate(a);ctx.strokeStyle='#c084fc';ctx.lineWidth=Math.max(10,s.r*.55);ctx.lineCap='round';ctx.beginPath();ctx.arc(0,0,s.r*1.35,-1.08,1.08);ctx.stroke();ctx.strokeStyle='#f0d9ff';ctx.lineWidth=Math.max(3,s.r*.16);ctx.beginPath();ctx.arc(0,0,s.r*1.34,-1.03,1.03);ctx.stroke()}else{ctx.beginPath();ctx.arc(0,0,s.r,0,Math.PI*2);ctx.fill()}ctx.restore()}
 for(const f of fistTrails){const k=clamp(f.life/f.max,0,1),ang=Math.atan2(f.dy,f.dx);ctx.save();ctx.translate(f.x,f.y);ctx.rotate(ang);ctx.globalAlpha=k*(f.finisher?.95:.82);ctx.scale(f.scale,f.scale);if(f.sharp){ctx.shadowBlur=20;ctx.shadowColor='#fff1a6';ctx.fillStyle='#fff8d2';ctx.beginPath();ctx.roundRect(-58,-8,87,16,8);ctx.fill();ctx.beginPath();ctx.arc(29,0,9,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffffff';ctx.beginPath();ctx.roundRect(-48,-3,77,6,3);ctx.fill();ctx.beginPath();ctx.arc(29,0,4,0,Math.PI*2);ctx.fill()}else{ctx.shadowBlur=f.finisher?22:12;ctx.shadowColor='#fff1bd';ctx.fillStyle='#fffdf5';ctx.strokeStyle='#b8c3cc';ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(-31,-12,30,24,7);ctx.fill();ctx.stroke();ctx.strokeStyle='#9eaab4';ctx.lineWidth=2;for(let b=-25;b<=-7;b+=7){ctx.beginPath();ctx.moveTo(b,-10);ctx.lineTo(b+4,10);ctx.stroke()}ctx.fillStyle='#fffdf5';ctx.beginPath();ctx.ellipse(9,0,f.finisher?24:20,f.finisher?21:17,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.arc(16,8,f.finisher?9:7,.15,Math.PI*1.35);ctx.stroke();ctx.strokeStyle='#d5dde3';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-9);ctx.quadraticCurveTo(8,-14,18,-8);ctx.moveTo(2,-2);ctx.quadraticCurveTo(12,-7,23,-1);ctx.stroke()}ctx.restore()}
 for(const q of holyFx){const k=clamp(q.life/q.max,0,1);ctx.save();ctx.translate(q.x,q.y);ctx.globalAlpha=k*.85;ctx.strokeStyle='#fff2a8';ctx.shadowBlur=24;ctx.shadowColor='#ffe066';ctx.lineWidth=q.wide?28:(q.big?16:11);if(q.type==='iceSpike'){ctx.fillStyle='#bcefff';ctx.strokeStyle='#e8fbff';ctx.lineWidth=3;for(let k=-2;k<=2;k++){const x=k*18,h=q.r*(.65+Math.abs(k)*.12);ctx.beginPath();ctx.moveTo(x-12,20);ctx.lineTo(x,-h);ctx.lineTo(x+12,20);ctx.closePath();ctx.fill();ctx.stroke()}}else if(q.type==='cross'){ctx.beginPath();ctx.moveTo(-q.r,0);ctx.lineTo(q.r,0);ctx.moveTo(0,-q.r);ctx.lineTo(0,q.r);ctx.stroke()}else{ctx.beginPath();ctx.arc(0,0,q.r*(1.15-k*.15),0,Math.PI*2);ctx.stroke()}ctx.restore()}
 for(const q of slashes){const k=clamp(q.life/q.max,0,1);ctx.save();ctx.translate(q.x,q.y);if(q.dragonThrust||q.clawMark)ctx.rotate(q.angle||0);else ctx.scale(q.side||1,1);ctx.globalAlpha=k;ctx.strokeStyle='#edf7ff';ctx.lineWidth=15*k+4;if(q.magic){ctx.strokeStyle='#c084fc';ctx.shadowBlur=18;ctx.shadowColor='#a855f7'}if(q.clawMark){const len=q.length||280;ctx.strokeStyle='#c47aff';ctx.shadowBlur=14;ctx.shadowColor='#8d43ce';ctx.lineCap='round';for(const off of [-13,0,13]){ctx.lineWidth=5*k+2;ctx.beginPath();ctx.moveTo(-len/2,off-10);ctx.lineTo(len/2,off+10);ctx.stroke();ctx.strokeStyle='#efcaff';ctx.lineWidth=1.6;ctx.stroke();ctx.strokeStyle='#c47aff'}}else if(q.ninjaDash){ctx.strokeStyle=q.bushinLine?'#6f1118':'#9fc5ff';ctx.shadowBlur=q.bushinLine?10:18;ctx.shadowColor=q.bushinLine?'#b92a32':'#6ea0ff';ctx.lineWidth=(q.bushinLine?14:18)*k+5;ctx.beginPath();ctx.moveTo(-q.length/2,0);ctx.lineTo(q.length/2,0);ctx.stroke();ctx.strokeStyle=q.bushinLine?'#d8b2a0':'#f4f8ff';ctx.lineWidth=q.bushinLine?4:5;ctx.stroke()}else if(q.dragonThrust){const len=q.length||285,tail=-len*.5,tip=len*.5;ctx.shadowBlur=20;ctx.shadowColor='#55bfff';ctx.lineCap='round';ctx.globalAlpha=k*.32;ctx.strokeStyle='#8edaff';ctx.lineWidth=20;ctx.beginPath();ctx.moveTo(tail,12);ctx.lineTo(tip-18,1);ctx.stroke();ctx.globalAlpha=k*.48;ctx.strokeStyle='#bcecff';ctx.lineWidth=10;ctx.beginPath();ctx.moveTo(tail-12,-10);ctx.lineTo(tip-7,-1);ctx.stroke();ctx.globalAlpha=k;ctx.fillStyle='#eafbff';ctx.beginPath();ctx.moveTo(tail,0);ctx.lineTo(tip-30,-8);ctx.lineTo(tip,0);ctx.lineTo(tip-30,8);ctx.closePath();ctx.fill();ctx.strokeStyle='#ffffff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(tail+12,0);ctx.lineTo(tip-5,0);ctx.stroke()}else if(q.spin){ctx.beginPath();ctx.arc(0,0,145,0,Math.PI*2);ctx.stroke();ctx.strokeStyle=q.magic?'#e9d5ff':'#9edbff';ctx.lineWidth=6;ctx.beginPath();ctx.arc(0,0,122,0,Math.PI*2);ctx.stroke()}else{ctx.beginPath();ctx.arc(0,0,96,-1.05,1.05);ctx.stroke();ctx.strokeStyle=q.magic?'#e9d5ff':'#9edbff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,113,-.9,.9);ctx.stroke()}ctx.restore()}
 for(const l of bloodBeams){ctx.save();ctx.globalAlpha=.9;ctx.strokeStyle=l.hit?'#d41446':'#8d1738';ctx.shadowBlur=6;ctx.shadowColor='#ff174f';ctx.lineCap='round';ctx.lineWidth=l.width;ctx.beginPath();ctx.moveTo(l.x,l.y);ctx.lineTo(l.x+l.dx*760,l.y+l.dy*760);ctx.stroke();ctx.strokeStyle='#ff9ab3';ctx.lineWidth=Math.max(1,l.width*.32);ctx.stroke();ctx.restore()}
 for(const l of lasers){const k=clamp(l.life/l.max,0,1);ctx.save();ctx.globalAlpha=.45+.5*k;ctx.strokeStyle='#fffbd0';ctx.shadowBlur=28;ctx.shadowColor='#fff4a8';ctx.lineWidth=l.width*k+8;ctx.beginPath();ctx.moveTo(l.x,l.y);ctx.lineTo(l.x+l.dx*1100,l.y+l.dy*1100);ctx.stroke();ctx.strokeStyle='#ffffff';ctx.lineWidth=Math.max(4,l.width*.32*k);ctx.stroke();ctx.restore()}
 for(const p of particles){ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle=p.c;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}
 drawTimeStopOverlay();
 ctx.restore();ctx.globalAlpha=1
}
let fatalErrorShown=false;
function showRuntimeError(err){
 console.error(err);
 if(fatalErrorShown)return;
 fatalErrorShown=true;running=false;
 const msg=err&&err.message?err.message:String(err);
 notice('エラーを検出しました: '+msg,'#ff8f9b',5000);
 const status=document.getElementById('loadStatus');
 if(status)status.textContent='動作エラー: '+msg+'（ページ再読込後も出る場合はこの表示をお知らせください）';
 setTimeout(()=>{ui.start.style.display='grid'},500);
}
window.addEventListener('error',e=>showRuntimeError(e.error||new Error(e.message)));
window.addEventListener('unhandledrejection',e=>showRuntimeError(e.reason||new Error('Promise error')));
function drawTimeStopOverlay(){if(timeStop<=0)return;ctx.save();ctx.fillStyle='rgba(150,210,255,.13)';ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(225,245,255,.72)';ctx.lineWidth=5;ctx.beginPath();ctx.arc(500,500,430,0,Math.PI*2);ctx.stroke();ctx.fillStyle='rgba(240,250,255,.9)';ctx.font='bold 32px sans-serif';ctx.textAlign='center';ctx.fillText('TIME STOP',500,92);ctx.restore()}


function loop(t){
 const dt=Math.min(.033,(t-last)/1000||0);last=t;
 try{if(running)update(dt);draw()}catch(err){showRuntimeError(err)}
 requestAnimationFrame(loop)
}
addEventListener('keydown',e=>{if(!keys.has(e.code))pressed.add(e.code);keys.add(e.code);if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault()});addEventListener('keyup',e=>{keys.delete(e.code);released.add(e.code)});
const joyEl=document.getElementById('joystick'),stick=document.getElementById('stick');function joyMove(e){const r=joyEl.getBoundingClientRect(),p=[...e.changedTouches].find(t=>t.identifier===joy.id);if(!p)return;let x=p.clientX-(r.left+r.width/2),y=p.clientY-(r.top+r.height/2),d=Math.hypot(x,y),m=r.width*.34;if(d>m){x=x/d*m;y=y/d*m}joy.x=x/m;joy.y=y/m;stick.style.transform=`translate(${x}px,${y}px)`}joyEl.addEventListener('touchstart',e=>{const t=e.changedTouches[0];joy.id=t.identifier;joyMove(e);e.preventDefault()},{passive:false});joyEl.addEventListener('touchmove',e=>{joyMove(e);e.preventDefault()},{passive:false});joyEl.addEventListener('touchend',e=>{joy.x=joy.y=0;joy.id=null;stick.style.transform='translate(0,0)';e.preventDefault()},{passive:false});
